# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190115_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
