# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-17 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190117_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='is_active',
        ),
    ]
